services:
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api/src/:/home/amir/app/src/
    env_file:
      - .env
    restart: always
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: ./docker/mongo/Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - ./api/db/:/data/db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: ${DB_PORT}
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
