FROM node:20.17-slim AS builder

WORKDIR /home/amir/app/src/

COPY ./api/src/ .

RUN npm ci --ignore-scripts

RUN npm run build


FROM node:20.17-slim AS production

WORKDIR /home/amir/app/src/

COPY --from=builder  /home/amir/app/src/dist . 

ENV TZ=Europe/Paris

EXPOSE 3000

USER node

CMD ["node", "app.js"]